import image_6 from '../../images/image 6.png';
import image_1 from '../../images/image_1.png';
import image_2 from '../../images/image 2.png';
import image_3 from '../../images/image 3.png';
import image_4 from '../../images/image 4.png';
import image_5 from '../../images/image 5.png';
import image_7 from '../../images/image 7.png';
import image_8 from '../../images/image 8.png';
import image_9 from '../../images/image 9.png';
import image_10 from '../../images/image 10.png';
import image_11 from '../../images/image 11.png';
import imghead from '../../images/Frame-2.png';
import imgmeet from '../../images/meet1.png';
import imgmeet2 from '../../images/meet3.png';
import home from '../../images/homepng.png';
import createDeThi from '../../images/createDeThi.png';
import imgRanMatch1 from '../../images/imgRanMatch1.png';
import imgRanMatch2 from '../../images/imgRanMatch2.png';
import imgRanMatch3 from '../../images/imgRanMatch3.png';
import imgRanMatch4 from '../../images/imgRanMatch4.jpg';
import imgRanMatch5 from '../../images/imgRanMatch5.jpg';
import imgRanMatch6 from '../../images/imgRanMatch6.jpg';

export  {home, image_1, image_2, image_3, image_4, image_5, image_6, image_7, image_8, image_9, image_10, image_11, imghead, imgmeet, imgmeet2, createDeThi, imgRanMatch1, imgRanMatch2, imgRanMatch3, imgRanMatch4, imgRanMatch5, imgRanMatch6 };